# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InterfaceBaseProbn.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(609, 514)
        MainWindow.setStyleSheet("background-color: rgb(188, 255, 207);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 0, 531, 321))
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 330, 161, 61))
        self.pushButton.setStyleSheet("font: 75 20pt \"Times New Roman\";\n"
"color: rgb(44, 130, 66);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(180, 330, 161, 61))
        self.pushButton_2.setStyleSheet("font: 75 20pt \"Times New Roman\";\n"
"color: rgb(44, 130, 66);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(350, 330, 161, 61))
        self.pushButton_3.setStyleSheet("font: 75 20pt \"Times New Roman\";\n"
"color: rgb(44, 130, 66);")
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 609, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.appendd()
        self.pushButton.clicked.connect(self.dobav)
        self.pushButton_2.clicked.connect(self.dele)
        self.pushButton_3.clicked.connect(self.upd)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Добавить"))
        self.pushButton_2.setText(_translate("MainWindow", "Удалить"))
        self.pushButton_3.setText(_translate("MainWindow", "Обновить"))
    def dobav(self): #Добавить запись
        row = self.tableWidget.rowCount()
        self.tableWidget.insertRow(row)
        
    def dele(self): #Удалить запись
        selected_items = self.tableWidget.selectedItems()

        if not selected_items:
            showerror("Ошибка","Выберите поле")
            return

        row = selected_items[0].row() #Номер строки
        self.tableWidget.removeRow(row)
        print("Удалила строку")
    def upd(self): #Обновить запись
        conn = sqlite3.connect('baseInterface')
        cursor = conn.cursor()
        cursor.execute("DELETE FROM Ученики")
        for i in range(self.tableWidget.rowCount()):
            row = []
            for j in range(self.tableWidget.columnCount()):
                cell = self.tableWidget.item(i,j)
                
                row.append(cell.text() if cell else "")
                
            cursor.execute("INSERT INTO Ученики VALUES(?,?,?,?,?)", row)
        conn.commit() #Сохранить соед.
        conn.close() #Закрыть соед.
    def appendd(self):
        conn = sqlite3.connect('baseInterface')
        cursor = conn.cursor()
        cursor.execute("SELECT * FROM Ученики")
        rows = cursor.fetchall()

        self.tableWidget.setRowCount(len(rows))
        self.tableWidget.setColumnCount(len(rows[0]) if rows else 0)

        for i, row in enumerate(rows):
            for j, value in enumerate(row):
                self.tableWidget.setItem(i, j, QtWidgets.QTableWidgetItem(str(value)))

        conn.close()
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
