# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(421, 326)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Downloads/free-icon-open-book-2702134.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(320, 10, 91, 31))
        self.pushButton.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"\n"
"background-color: rgb(103, 186, 128);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 200, 111, 61))
        self.pushButton_2.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"\n"
"background-color: rgb(103, 186, 128);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(150, 200, 121, 61))
        self.pushButton_3.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"\n"
"background-color: rgb(103, 186, 128);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(280, 200, 111, 61))
        self.pushButton_4.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"\n"
"background-color: rgb(103, 186, 128);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 10, 121, 100))
        self.label.setMinimumSize(QtCore.QSize(100, 100))
        self.label.setStyleSheet("font: 18pt \"Impact\";")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../../Downloads/free-icon-open-book-2702134.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(60, 130, 311, 41))
        self.label_2.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.pushButton.clicked.connect(self.ex)
        self.pushButton_2.clicked.connect(self.TableKnigi)
        #self.pushButton_3.clicked.connect(self.TableOptBuy)
        #self.pushButton_4.clicked.connect(self.TableZakaz)
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Выбор таблицы"))
        self.pushButton.setText(_translate("Form", "Выход"))
        self.pushButton_2.setText(_translate("Form", "Книги"))
        self.pushButton_3.setText(_translate("Form", "Оптовые \n"
"покупатели"))
        self.pushButton_4.setText(_translate("Form", "Заказики"))
        self.label_2.setText(_translate("Form", "Выберите таблицу для изучения"))
    def ex(self):
        Form.close()
    def TableKnigi(self):
        os.startfile("mainlogic.py")
    #def TableOptBuy(self):
    #def TableZakaz(self):
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
